IP_SOCKET: '127.0.0.1' # endereço IP que o servidor vai rodar
PORTA_SOCKET: 8888 # porta que o servidor vai rodar
TAMANHO_MAXIMO_PACOTE: 3134 # 3Kb tamanho máximo do dado enviado a cada vez
BASH: xfce4-terminal
BASH_PARAMS: --geometry 60x10 --title 'Servidor {}'
PYTHON: /usr/bin/python3
SERVIDORES: ./servidores.txt
DB_PARAMS: ./db_params.yaml
PREFIXO_PORTA: '199'
DIR_LOG: 'logs/'
DIR_SNAP: 'snaps/'
SLEEP_TIME : 10
