# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0finterface.proto\"\'\n\x07msgItem\x12\r\n\x05\x63have\x18\x01 \x01(\x03\x12\r\n\x05valor\x18\x02 \x01(\t\":\n\x06status\x12\x10\n\x08resposta\x18\x01 \x01(\t\x12\x1e\n\x0citemResposta\x18\x02 \x01(\x0b\x32\x08.msgItem2\x96\x01\n\x0cManipulaMapa\x12\x1f\n\x08\x43riaItem\x12\x08.msgItem\x1a\x07.status\"\x00\x12\x1d\n\x06LeItem\x12\x08.msgItem\x1a\x07.status\"\x00\x12#\n\x0c\x41tualizaItem\x12\x08.msgItem\x1a\x07.status\"\x00\x12!\n\nDeletaItem\x12\x08.msgItem\x1a\x07.status\"\x00\x62\x06proto3')
)




_MSGITEM = _descriptor.Descriptor(
  name='msgItem',
  full_name='msgItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='msgItem.chave', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='msgItem.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=58,
)


_STATUS = _descriptor.Descriptor(
  name='status',
  full_name='status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resposta', full_name='status.resposta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemResposta', full_name='status.itemResposta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=118,
)

_STATUS.fields_by_name['itemResposta'].message_type = _MSGITEM
DESCRIPTOR.message_types_by_name['msgItem'] = _MSGITEM
DESCRIPTOR.message_types_by_name['status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgItem = _reflection.GeneratedProtocolMessageType('msgItem', (_message.Message,), dict(
  DESCRIPTOR = _MSGITEM,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:msgItem)
  ))
_sym_db.RegisterMessage(msgItem)

status = _reflection.GeneratedProtocolMessageType('status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'interface_pb2'
  # @@protoc_insertion_point(class_scope:status)
  ))
_sym_db.RegisterMessage(status)



_MANIPULAMAPA = _descriptor.ServiceDescriptor(
  name='ManipulaMapa',
  full_name='ManipulaMapa',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=121,
  serialized_end=271,
  methods=[
  _descriptor.MethodDescriptor(
    name='CriaItem',
    full_name='ManipulaMapa.CriaItem',
    index=0,
    containing_service=None,
    input_type=_MSGITEM,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LeItem',
    full_name='ManipulaMapa.LeItem',
    index=1,
    containing_service=None,
    input_type=_MSGITEM,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AtualizaItem',
    full_name='ManipulaMapa.AtualizaItem',
    index=2,
    containing_service=None,
    input_type=_MSGITEM,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeletaItem',
    full_name='ManipulaMapa.DeletaItem',
    index=3,
    containing_service=None,
    input_type=_MSGITEM,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANIPULAMAPA)

DESCRIPTOR.services_by_name['ManipulaMapa'] = _MANIPULAMAPA

# @@protoc_insertion_point(module_scope)
