# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remotedb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remotedb.proto',
  package='remotedb',
  syntax='proto3',
  serialized_options=_b('\n\020io.grpc.remotedbB\rRemoteDBProtoP\001\242\002\003RDB'),
  serialized_pb=_b('\n\x0eremotedb.proto\x12\x08remotedb\")\n\tKVRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\"\x19\n\x08KRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"\t\n\x07Request\"\x1f\n\x0bServerReply\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\x9f\x02\n\x08RemoteDB\x12\x36\n\x06\x63reate\x12\x13.remotedb.KVRequest\x1a\x15.remotedb.ServerReply\"\x00\x12\x33\n\x04read\x12\x12.remotedb.KRequest\x1a\x15.remotedb.ServerReply\"\x00\x12\x36\n\x06update\x12\x13.remotedb.KVRequest\x1a\x15.remotedb.ServerReply\"\x00\x12\x35\n\x06\x64\x65lete\x12\x12.remotedb.KRequest\x1a\x15.remotedb.ServerReply\"\x00\x12\x37\n\tget_range\x12\x11.remotedb.Request\x1a\x15.remotedb.ServerReply\"\x00\x42)\n\x10io.grpc.remotedbB\rRemoteDBProtoP\x01\xa2\x02\x03RDBb\x06proto3')
)




_KVREQUEST = _descriptor.Descriptor(
  name='KVRequest',
  full_name='remotedb.KVRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='remotedb.KVRequest.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='remotedb.KVRequest.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=69,
)


_KREQUEST = _descriptor.Descriptor(
  name='KRequest',
  full_name='remotedb.KRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='remotedb.KRequest.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=96,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='remotedb.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=107,
)


_SERVERREPLY = _descriptor.Descriptor(
  name='ServerReply',
  full_name='remotedb.ServerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensagem', full_name='remotedb.ServerReply.mensagem', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['KVRequest'] = _KVREQUEST
DESCRIPTOR.message_types_by_name['KRequest'] = _KREQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['ServerReply'] = _SERVERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KVRequest = _reflection.GeneratedProtocolMessageType('KVRequest', (_message.Message,), dict(
  DESCRIPTOR = _KVREQUEST,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.KVRequest)
  ))
_sym_db.RegisterMessage(KVRequest)

KRequest = _reflection.GeneratedProtocolMessageType('KRequest', (_message.Message,), dict(
  DESCRIPTOR = _KREQUEST,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.KRequest)
  ))
_sym_db.RegisterMessage(KRequest)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.Request)
  ))
_sym_db.RegisterMessage(Request)

ServerReply = _reflection.GeneratedProtocolMessageType('ServerReply', (_message.Message,), dict(
  DESCRIPTOR = _SERVERREPLY,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.ServerReply)
  ))
_sym_db.RegisterMessage(ServerReply)


DESCRIPTOR._options = None

_REMOTEDB = _descriptor.ServiceDescriptor(
  name='RemoteDB',
  full_name='remotedb.RemoteDB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=143,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='remotedb.RemoteDB.create',
    index=0,
    containing_service=None,
    input_type=_KVREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='remotedb.RemoteDB.read',
    index=1,
    containing_service=None,
    input_type=_KREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='remotedb.RemoteDB.update',
    index=2,
    containing_service=None,
    input_type=_KVREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='remotedb.RemoteDB.delete',
    index=3,
    containing_service=None,
    input_type=_KREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_range',
    full_name='remotedb.RemoteDB.get_range',
    index=4,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTEDB)

DESCRIPTOR.services_by_name['RemoteDB'] = _REMOTEDB

# @@protoc_insertion_point(module_scope)
