# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import remotedb_pb2 as remotedb__pb2


class RemoteDBStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/remotedb.RemoteDB/create',
        request_serializer=remotedb__pb2.CreateRequest.SerializeToString,
        response_deserializer=remotedb__pb2.ServerReply.FromString,
        )
    self.read = channel.unary_unary(
        '/remotedb.RemoteDB/read',
        request_serializer=remotedb__pb2.ReadRequest.SerializeToString,
        response_deserializer=remotedb__pb2.ServerReply.FromString,
        )
    self.update = channel.unary_unary(
        '/remotedb.RemoteDB/update',
        request_serializer=remotedb__pb2.UpdateRequest.SerializeToString,
        response_deserializer=remotedb__pb2.ServerReply.FromString,
        )
    self.delete = channel.unary_unary(
        '/remotedb.RemoteDB/delete',
        request_serializer=remotedb__pb2.DeleteRequest.SerializeToString,
        response_deserializer=remotedb__pb2.ServerReply.FromString,
        )


class RemoteDBServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    """create
    ------
    Cria uma nova entrada no banco de dados associando uma entrada a
    uma chave inteira.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def read(self, request, context):
    """read
    ----
    Le um registro do banco. Dado uma chave, retorna um registro
    associado a chave ou null.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    """update
    ------
    Atualiza um registro no banco de dados. Dado uma chave e um novo
    valor, a aplicacao deve atualizar o valor, se ele existir.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    """delete
    ------
    Apaga um registro do banco de dados.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoteDBServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=remotedb__pb2.CreateRequest.FromString,
          response_serializer=remotedb__pb2.ServerReply.SerializeToString,
      ),
      'read': grpc.unary_unary_rpc_method_handler(
          servicer.read,
          request_deserializer=remotedb__pb2.ReadRequest.FromString,
          response_serializer=remotedb__pb2.ServerReply.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=remotedb__pb2.UpdateRequest.FromString,
          response_serializer=remotedb__pb2.ServerReply.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=remotedb__pb2.DeleteRequest.FromString,
          response_serializer=remotedb__pb2.ServerReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'remotedb.RemoteDB', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
