# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remotedb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remotedb.proto',
  package='remotedb',
  syntax='proto3',
  serialized_options=_b('\n\020io.grpc.remotedbB\rRemoteDBProtoP\001\242\002\003RDB'),
  serialized_pb=_b('\n\x0eremotedb.proto\x12\x08remotedb\"-\n\rCreateRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\"\x1c\n\x0bReadRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"-\n\rUpdateRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\"\x1e\n\rDeleteRequest\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"\x1f\n\x0bServerReply\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\xf6\x01\n\x08RemoteDB\x12:\n\x06\x43reate\x12\x17.remotedb.CreateRequest\x1a\x15.remotedb.ServerReply\"\x00\x12\x36\n\x04Read\x12\x15.remotedb.ReadRequest\x1a\x15.remotedb.ServerReply\"\x00\x12:\n\x06Update\x12\x17.remotedb.UpdateRequest\x1a\x15.remotedb.ServerReply\"\x00\x12:\n\x06\x44\x65lete\x12\x17.remotedb.DeleteRequest\x1a\x15.remotedb.ServerReply\"\x00\x42)\n\x10io.grpc.remotedbB\rRemoteDBProtoP\x01\xa2\x02\x03RDBb\x06proto3')
)




_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='remotedb.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='remotedb.CreateRequest.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='remotedb.CreateRequest.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=73,
)


_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='remotedb.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='remotedb.ReadRequest.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=103,
)


_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='remotedb.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='remotedb.UpdateRequest.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='remotedb.UpdateRequest.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=150,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='remotedb.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='remotedb.DeleteRequest.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=182,
)


_SERVERREPLY = _descriptor.Descriptor(
  name='ServerReply',
  full_name='remotedb.ServerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensagem', full_name='remotedb.ServerReply.mensagem', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=215,
)

DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
DESCRIPTOR.message_types_by_name['ServerReply'] = _SERVERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEREQUEST,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.CreateRequest)
  ))
_sym_db.RegisterMessage(CreateRequest)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), dict(
  DESCRIPTOR = _READREQUEST,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.ReadRequest)
  ))
_sym_db.RegisterMessage(ReadRequest)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEREQUEST,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.UpdateRequest)
  ))
_sym_db.RegisterMessage(UpdateRequest)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEREQUEST,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.DeleteRequest)
  ))
_sym_db.RegisterMessage(DeleteRequest)

ServerReply = _reflection.GeneratedProtocolMessageType('ServerReply', (_message.Message,), dict(
  DESCRIPTOR = _SERVERREPLY,
  __module__ = 'remotedb_pb2'
  # @@protoc_insertion_point(class_scope:remotedb.ServerReply)
  ))
_sym_db.RegisterMessage(ServerReply)


DESCRIPTOR._options = None

_REMOTEDB = _descriptor.ServiceDescriptor(
  name='RemoteDB',
  full_name='remotedb.RemoteDB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=218,
  serialized_end=464,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='remotedb.RemoteDB.Create',
    index=0,
    containing_service=None,
    input_type=_CREATEREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='remotedb.RemoteDB.Read',
    index=1,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='remotedb.RemoteDB.Update',
    index=2,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='remotedb.RemoteDB.Delete',
    index=3,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=_SERVERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTEDB)

DESCRIPTOR.services_by_name['RemoteDB'] = _REMOTEDB

# @@protoc_insertion_point(module_scope)
