// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package org.trabalhoSD2.grpc;

public interface OperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.trabalhoSD2.grpc.Operation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 operation = 1;</code>
   */
  int getOperation();

  /**
   * <code>int32 keyLength = 2;</code>
   */
  int getKeyLength();

  /**
   * <code>int32 key = 3;</code>
   */
  int getKey();

  /**
   * <code>int32 valueLength = 4;</code>
   */
  int getValueLength();

  /**
   * <code>string value = 5;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 5;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
