// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package org.trabalhoSD2.grpc;

/**
 * Protobuf type {@code org.trabalhoSD2.grpc.Operation}
 */
public  final class Operation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.trabalhoSD2.grpc.Operation)
    OperationOrBuilder {
  // Use Operation.newBuilder() to construct.
  private Operation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Operation() {
    operation_ = 0;
    keyLength_ = 0;
    key_ = 0;
    valueLength_ = 0;
    value_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Operation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            operation_ = input.readInt32();
            break;
          }
          case 16: {

            keyLength_ = input.readInt32();
            break;
          }
          case 24: {

            key_ = input.readInt32();
            break;
          }
          case 32: {

            valueLength_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.trabalhoSD2.grpc.Service.internal_static_org_trabalhoSD2_grpc_Operation_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.trabalhoSD2.grpc.Service.internal_static_org_trabalhoSD2_grpc_Operation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.trabalhoSD2.grpc.Operation.class, org.trabalhoSD2.grpc.Operation.Builder.class);
  }

  public static final int OPERATION_FIELD_NUMBER = 1;
  private int operation_;
  /**
   * <code>int32 operation = 1;</code>
   */
  public int getOperation() {
    return operation_;
  }

  public static final int KEYLENGTH_FIELD_NUMBER = 2;
  private int keyLength_;
  /**
   * <code>int32 keyLength = 2;</code>
   */
  public int getKeyLength() {
    return keyLength_;
  }

  public static final int KEY_FIELD_NUMBER = 3;
  private int key_;
  /**
   * <code>int32 key = 3;</code>
   */
  public int getKey() {
    return key_;
  }

  public static final int VALUELENGTH_FIELD_NUMBER = 4;
  private int valueLength_;
  /**
   * <code>int32 valueLength = 4;</code>
   */
  public int getValueLength() {
    return valueLength_;
  }

  public static final int VALUE_FIELD_NUMBER = 5;
  private volatile java.lang.Object value_;
  /**
   * <code>string value = 5;</code>
   */
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string value = 5;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (operation_ != 0) {
      output.writeInt32(1, operation_);
    }
    if (keyLength_ != 0) {
      output.writeInt32(2, keyLength_);
    }
    if (key_ != 0) {
      output.writeInt32(3, key_);
    }
    if (valueLength_ != 0) {
      output.writeInt32(4, valueLength_);
    }
    if (!getValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, value_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (operation_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, operation_);
    }
    if (keyLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, keyLength_);
    }
    if (key_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, key_);
    }
    if (valueLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, valueLength_);
    }
    if (!getValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, value_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.trabalhoSD2.grpc.Operation)) {
      return super.equals(obj);
    }
    org.trabalhoSD2.grpc.Operation other = (org.trabalhoSD2.grpc.Operation) obj;

    boolean result = true;
    result = result && (getOperation()
        == other.getOperation());
    result = result && (getKeyLength()
        == other.getKeyLength());
    result = result && (getKey()
        == other.getKey());
    result = result && (getValueLength()
        == other.getValueLength());
    result = result && getValue()
        .equals(other.getValue());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + getOperation();
    hash = (37 * hash) + KEYLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getKeyLength();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey();
    hash = (37 * hash) + VALUELENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getValueLength();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.trabalhoSD2.grpc.Operation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.trabalhoSD2.grpc.Operation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.trabalhoSD2.grpc.Operation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.trabalhoSD2.grpc.Operation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.trabalhoSD2.grpc.Operation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.trabalhoSD2.grpc.Operation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.trabalhoSD2.grpc.Operation)
      org.trabalhoSD2.grpc.OperationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.trabalhoSD2.grpc.Service.internal_static_org_trabalhoSD2_grpc_Operation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.trabalhoSD2.grpc.Service.internal_static_org_trabalhoSD2_grpc_Operation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.trabalhoSD2.grpc.Operation.class, org.trabalhoSD2.grpc.Operation.Builder.class);
    }

    // Construct using org.trabalhoSD2.grpc.Operation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      operation_ = 0;

      keyLength_ = 0;

      key_ = 0;

      valueLength_ = 0;

      value_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.trabalhoSD2.grpc.Service.internal_static_org_trabalhoSD2_grpc_Operation_descriptor;
    }

    public org.trabalhoSD2.grpc.Operation getDefaultInstanceForType() {
      return org.trabalhoSD2.grpc.Operation.getDefaultInstance();
    }

    public org.trabalhoSD2.grpc.Operation build() {
      org.trabalhoSD2.grpc.Operation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.trabalhoSD2.grpc.Operation buildPartial() {
      org.trabalhoSD2.grpc.Operation result = new org.trabalhoSD2.grpc.Operation(this);
      result.operation_ = operation_;
      result.keyLength_ = keyLength_;
      result.key_ = key_;
      result.valueLength_ = valueLength_;
      result.value_ = value_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.trabalhoSD2.grpc.Operation) {
        return mergeFrom((org.trabalhoSD2.grpc.Operation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.trabalhoSD2.grpc.Operation other) {
      if (other == org.trabalhoSD2.grpc.Operation.getDefaultInstance()) return this;
      if (other.getOperation() != 0) {
        setOperation(other.getOperation());
      }
      if (other.getKeyLength() != 0) {
        setKeyLength(other.getKeyLength());
      }
      if (other.getKey() != 0) {
        setKey(other.getKey());
      }
      if (other.getValueLength() != 0) {
        setValueLength(other.getValueLength());
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.trabalhoSD2.grpc.Operation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.trabalhoSD2.grpc.Operation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int operation_ ;
    /**
     * <code>int32 operation = 1;</code>
     */
    public int getOperation() {
      return operation_;
    }
    /**
     * <code>int32 operation = 1;</code>
     */
    public Builder setOperation(int value) {
      
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 operation = 1;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }

    private int keyLength_ ;
    /**
     * <code>int32 keyLength = 2;</code>
     */
    public int getKeyLength() {
      return keyLength_;
    }
    /**
     * <code>int32 keyLength = 2;</code>
     */
    public Builder setKeyLength(int value) {
      
      keyLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 keyLength = 2;</code>
     */
    public Builder clearKeyLength() {
      
      keyLength_ = 0;
      onChanged();
      return this;
    }

    private int key_ ;
    /**
     * <code>int32 key = 3;</code>
     */
    public int getKey() {
      return key_;
    }
    /**
     * <code>int32 key = 3;</code>
     */
    public Builder setKey(int value) {
      
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 key = 3;</code>
     */
    public Builder clearKey() {
      
      key_ = 0;
      onChanged();
      return this;
    }

    private int valueLength_ ;
    /**
     * <code>int32 valueLength = 4;</code>
     */
    public int getValueLength() {
      return valueLength_;
    }
    /**
     * <code>int32 valueLength = 4;</code>
     */
    public Builder setValueLength(int value) {
      
      valueLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 valueLength = 4;</code>
     */
    public Builder clearValueLength() {
      
      valueLength_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <code>string value = 5;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value = 5;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value = 5;</code>
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string value = 5;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.trabalhoSD2.grpc.Operation)
  }

  // @@protoc_insertion_point(class_scope:org.trabalhoSD2.grpc.Operation)
  private static final org.trabalhoSD2.grpc.Operation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.trabalhoSD2.grpc.Operation();
  }

  public static org.trabalhoSD2.grpc.Operation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Operation>
      PARSER = new com.google.protobuf.AbstractParser<Operation>() {
    public Operation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Operation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Operation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Operation> getParserForType() {
    return PARSER;
  }

  public org.trabalhoSD2.grpc.Operation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

