// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package org.trabalhoSD2.grpc;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_trabalhoSD2_grpc_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_trabalhoSD2_grpc_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_trabalhoSD2_grpc_OperationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_trabalhoSD2_grpc_OperationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rService.proto\022\024org.trabalhoSD2.grpc\"b\n" +
      "\tOperation\022\021\n\toperation\030\001 \001(\005\022\021\n\tkeyLeng" +
      "th\030\002 \001(\005\022\013\n\003key\030\003 \001(\005\022\023\n\013valueLength\030\004 \001" +
      "(\005\022\r\n\005value\030\005 \001(\t\"4\n\021OperationResponse\022\020" +
      "\n\010response\030\001 \001(\t\022\r\n\005value\030\002 \001(\t2l\n\rMakeO" +
      "peration\022[\n\rmakeOperation\022\037.org.trabalho" +
      "SD2.grpc.Operation\032\'.org.trabalhoSD2.grp" +
      "c.OperationResponse0\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_trabalhoSD2_grpc_Operation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_trabalhoSD2_grpc_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_trabalhoSD2_grpc_Operation_descriptor,
        new java.lang.String[] { "Operation", "KeyLength", "Key", "ValueLength", "Value", });
    internal_static_org_trabalhoSD2_grpc_OperationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_trabalhoSD2_grpc_OperationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_trabalhoSD2_grpc_OperationResponse_descriptor,
        new java.lang.String[] { "Response", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
