// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public final class GrpcProto {
  private GrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GenericRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GenericRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GenericResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GenericResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\",\n\016Generi" +
      "cRequest\022\014\n\004code\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\"@\n\017" +
      "GenericResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007messa" +
      "ge\030\002 \001(\t\022\014\n\004data\030\003 \001(\t2\252\002\n\007Greeter\022G\n\nCr" +
      "eateUser\022\032.helloworld.GenericRequest\032\033.h" +
      "elloworld.GenericResponse\"\000\022D\n\007GetUser\022\032" +
      ".helloworld.GenericRequest\032\033.helloworld." +
      "GenericResponse\"\000\022G\n\nUpdateUser\022\032.hellow" +
      "orld.GenericRequest\032\033.helloworld.Generic" +
      "Response\"\000\022G\n\nDeleteUser\022\032.helloworld.Ge" +
      "nericRequest\032\033.helloworld.GenericRespons" +
      "e\"\000B\034\n\007io.grpcB\tGrpcProtoP\001\242\002\003HLWb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_GenericRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_GenericRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GenericRequest_descriptor,
        new String[] { "Code", "Data", });
    internal_static_helloworld_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GenericResponse_descriptor,
        new String[] { "Status", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
