// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_CreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_DeleteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\")\n\rCreate" +
      "Request\022\n\n\002id\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\"1\n\016Cre" +
      "ateResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002" +
      " \001(\t\"\030\n\nGetRequest\022\n\n\002id\030\001 \001(\t\"\'\n\013GetRes" +
      "ponse\022\n\n\002id\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\")\n\rUpdat" +
      "eRequest\022\n\n\002id\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\"1\n\016Up" +
      "dateResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030" +
      "\002 \001(\t\"\033\n\rDeleteRequest\022\n\n\002id\030\001 \001(\t\"1\n\016De" +
      "leteResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030" +
      "\002 \001(\t2\234\002\n\007Greeter\022E\n\nCreateUser\022\031.hellow" +
      "orld.CreateRequest\032\032.helloworld.CreateRe" +
      "sponse\"\000\022<\n\007GetUser\022\026.helloworld.GetRequ" +
      "est\032\027.helloworld.GetResponse\"\000\022E\n\nUpdate" +
      "User\022\031.helloworld.UpdateRequest\032\032.hellow" +
      "orld.UpdateResponse\"\000\022E\n\nDeleteUser\022\031.he" +
      "lloworld.DeleteRequest\032\032.helloworld.Dele" +
      "teResponse\"\000B\"\n\007io.grpcB\017HelloWorldProto" +
      "P\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_CreateRequest_descriptor,
        new String[] { "Id", "Data", });
    internal_static_helloworld_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_CreateResponse_descriptor,
        new String[] { "Status", "Message", });
    internal_static_helloworld_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GetRequest_descriptor,
        new String[] { "Id", });
    internal_static_helloworld_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GetResponse_descriptor,
        new String[] { "Id", "Data", });
    internal_static_helloworld_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helloworld_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_UpdateRequest_descriptor,
        new String[] { "Id", "Data", });
    internal_static_helloworld_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_helloworld_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_UpdateResponse_descriptor,
        new String[] { "Status", "Message", });
    internal_static_helloworld_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_helloworld_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_DeleteRequest_descriptor,
        new String[] { "Id", });
    internal_static_helloworld_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_helloworld_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_DeleteResponse_descriptor,
        new String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
