// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string data = 2;</code>
   */
  String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
