// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public interface FindResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.FindResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool response = 1;</code>
   */
  boolean getResponse();

  /**
   * <code>string ip = 2;</code>
   */
  String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();
}
