// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer.proto

package io.grpc;

public interface FindMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.grpc.FindMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 key = 1;</code>
   */
  int getKey();
}
