// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public interface GenericRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GenericRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string data = 2;</code>
   */
  String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
