// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer.proto

package io.grpc;

public interface GetRangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.grpc.GetRangeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node = 1;</code>
   */
  String getNode();
  /**
   * <code>string node = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeBytes();

  /**
   * <code>string fingerT = 2;</code>
   */
  String getFingerT();
  /**
   * <code>string fingerT = 2;</code>
   */
  com.google.protobuf.ByteString
      getFingerTBytes();

  /**
   * <code>string range = 3;</code>
   */
  String getRange();
  /**
   * <code>string range = 3;</code>
   */
  com.google.protobuf.ByteString
      getRangeBytes();

  /**
   * <code>string data = 4;</code>
   */
  String getData();
  /**
   * <code>string data = 4;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
