// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public interface GetRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 node = 1;</code>
   */
  int getNode();
}
