// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public final class GrpcProto {
  private GrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GenericRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GenericRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GenericResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GenericResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_FindMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_FindMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_FindResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_FindResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GetRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GetRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GetRangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GetRangeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_UpdateFTRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_UpdateFTRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_UpdateFTResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_UpdateFTResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\",\n\016Generi" +
      "cRequest\022\014\n\004code\030\001 \001(\005\022\014\n\004data\030\002 \001(\t\"@\n\017" +
      "GenericResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007messa" +
      "ge\030\002 \001(\t\022\014\n\004data\030\003 \001(\t\"\032\n\013FindMessage\022\013\n" +
      "\003key\030\001 \001(\005\":\n\014FindResponse\022\020\n\010response\030\001" +
      " \001(\010\022\n\n\002ip\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"\037\n\017GetRan" +
      "geRequest\022\014\n\004node\030\001 \001(\t\"=\n\020GetRangeRespo" +
      "nse\022\014\n\004node\030\001 \001(\t\022\r\n\005range\030\002 \001(\t\022\014\n\004data" +
      "\030\003 \001(\t\"\"\n\017UpdateFTRequest\022\017\n\007fingerT\030\001 \001" +
      "(\t\"3\n\020UpdateFTResponse\022\017\n\007fingerT\030\001 \001(\t\022" +
      "\016\n\006update\030\002 \001(\0102\375\003\n\007Greeter\022G\n\nCreateUse" +
      "r\022\032.helloworld.GenericRequest\032\033.hellowor" +
      "ld.GenericResponse\"\000\022D\n\007GetUser\022\032.hellow" +
      "orld.GenericRequest\032\033.helloworld.Generic" +
      "Response\"\000\022G\n\nUpdateUser\022\032.helloworld.Ge" +
      "nericRequest\032\033.helloworld.GenericRespons" +
      "e\"\000\022G\n\nDeleteUser\022\032.helloworld.GenericRe" +
      "quest\032\033.helloworld.GenericResponse\"\000\022?\n\010" +
      "FindNode\022\027.helloworld.FindMessage\032\030.hell" +
      "oworld.FindResponse\"\000\022G\n\010GetRange\022\033.hell" +
      "oworld.GetRangeRequest\032\034.helloworld.GetR" +
      "angeResponse\"\000\022G\n\010UpdateFT\022\033.helloworld." +
      "UpdateFTRequest\032\034.helloworld.UpdateFTRes" +
      "ponse\"\000B\034\n\007io.grpcB\tGrpcProtoP\001\242\002\003HLWb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_GenericRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_GenericRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GenericRequest_descriptor,
        new String[] { "Code", "Data", });
    internal_static_helloworld_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GenericResponse_descriptor,
        new String[] { "Status", "Message", "Data", });
    internal_static_helloworld_FindMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_FindMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_FindMessage_descriptor,
        new String[] { "Key", });
    internal_static_helloworld_FindResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_FindResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_FindResponse_descriptor,
        new String[] { "Response", "Ip", "Port", });
    internal_static_helloworld_GetRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helloworld_GetRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GetRangeRequest_descriptor,
        new String[] { "Node", });
    internal_static_helloworld_GetRangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_helloworld_GetRangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GetRangeResponse_descriptor,
        new String[] { "Node", "Range", "Data", });
    internal_static_helloworld_UpdateFTRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_helloworld_UpdateFTRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_UpdateFTRequest_descriptor,
        new String[] { "FingerT", });
    internal_static_helloworld_UpdateFTResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_helloworld_UpdateFTResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_UpdateFTResponse_descriptor,
        new String[] { "FingerT", "Update", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
