// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer.proto

package io.grpc;

public interface NewNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.grpc.NewNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fingerT = 1;</code>
   */
  String getFingerT();
  /**
   * <code>string fingerT = 1;</code>
   */
  com.google.protobuf.ByteString
      getFingerTBytes();

  /**
   * <code>bool update = 2;</code>
   */
  boolean getUpdate();
}
