// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer.proto

package io.grpc;

public interface NewNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.grpc.NewNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node = 1;</code>
   */
  String getNode();
  /**
   * <code>string node = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeBytes();

  /**
   * <code>string newNode = 2;</code>
   */
  String getNewNode();
  /**
   * <code>string newNode = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewNodeBytes();
}
