// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer.proto

package io.grpc;

public interface SafeOutputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.grpc.SafeOutputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   */
  String getData();
  /**
   * <code>string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>string node = 2;</code>
   */
  String getNode();
  /**
   * <code>string node = 2;</code>
   */
  com.google.protobuf.ByteString
      getNodeBytes();
}
