// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc;

public interface UpdateFTRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.UpdateFTRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fingerT = 1;</code>
   */
  String getFingerT();
  /**
   * <code>string fingerT = 1;</code>
   */
  com.google.protobuf.ByteString
      getFingerTBytes();
}
