// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crud.proto

package com.example.grpc;

public interface ComandoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comando)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 chave = 1;</code>
   */
  long getChave();

  /**
   * <code>string valor = 2;</code>
   */
  java.lang.String getValor();
  /**
   * <code>string valor = 2;</code>
   */
  com.google.protobuf.ByteString
      getValorBytes();
}
