// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crud.proto

package com.example.grpc;

public final class Crud {
  private Crud() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Comando_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Comando_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncrud.proto\"\'\n\007Comando\022\r\n\005chave\030\001 \001(\003\022\r" +
      "\n\005valor\030\002 \001(\t\"\031\n\006Result\022\017\n\007message\030\001 \001(\t" +
      "2\200\001\n\004CRUD\022\035\n\006Create\022\010.Comando\032\007.Result\"\000" +
      "\022\033\n\004Read\022\010.Comando\032\007.Result\"\000\022\035\n\006Update\022" +
      "\010.Comando\032\007.Result\"\000\022\035\n\006Delete\022\010.Comando" +
      "\032\007.Result\"\000B\024\n\020com.example.grpcP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Comando_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Comando_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Comando_descriptor,
        new java.lang.String[] { "Chave", "Valor", });
    internal_static_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
