# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import definition_pb2 as definition__pb2


class OperacaoStub(object):
  """definição do serviço de CRUD ao banco de dados

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/Operacao/Create',
        request_serializer=definition__pb2.CreateUpdateRequest.SerializeToString,
        response_deserializer=definition__pb2.ResultReply.FromString,
        )
    self.Read = channel.unary_unary(
        '/Operacao/Read',
        request_serializer=definition__pb2.ReadDeleteRequest.SerializeToString,
        response_deserializer=definition__pb2.ResultReply.FromString,
        )
    self.Update = channel.unary_unary(
        '/Operacao/Update',
        request_serializer=definition__pb2.CreateUpdateRequest.SerializeToString,
        response_deserializer=definition__pb2.ResultReply.FromString,
        )
    self.Delete = channel.unary_unary(
        '/Operacao/Delete',
        request_serializer=definition__pb2.ReadDeleteRequest.SerializeToString,
        response_deserializer=definition__pb2.ResultReply.FromString,
        )


class OperacaoServicer(object):
  """definição do serviço de CRUD ao banco de dados

  """

  def Create(self, request, context):
    """realiza uma operação no banco de dados
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OperacaoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=definition__pb2.CreateUpdateRequest.FromString,
          response_serializer=definition__pb2.ResultReply.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=definition__pb2.ReadDeleteRequest.FromString,
          response_serializer=definition__pb2.ResultReply.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=definition__pb2.CreateUpdateRequest.FromString,
          response_serializer=definition__pb2.ResultReply.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=definition__pb2.ReadDeleteRequest.FromString,
          response_serializer=definition__pb2.ResultReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Operacao', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
