# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import map_pb2 as map__pb2


class MapStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendGrpc = channel.unary_unary(
        '/Map/SendGrpc',
        request_serializer=map__pb2.Message.SerializeToString,
        response_deserializer=map__pb2.Response.FromString,
        )
    self.LogTest = channel.unary_unary(
        '/Map/LogTest',
        request_serializer=map__pb2.Message.SerializeToString,
        response_deserializer=map__pb2.Data.FromString,
        )
    self.Create = channel.unary_unary(
        '/Map/Create',
        request_serializer=map__pb2.Message.SerializeToString,
        response_deserializer=map__pb2.Response.FromString,
        )
    self.Retrieve = channel.unary_unary(
        '/Map/Retrieve',
        request_serializer=map__pb2.Message.SerializeToString,
        response_deserializer=map__pb2.Response.FromString,
        )
    self.Update = channel.unary_unary(
        '/Map/Update',
        request_serializer=map__pb2.Message.SerializeToString,
        response_deserializer=map__pb2.Response.FromString,
        )
    self.Delete = channel.unary_unary(
        '/Map/Delete',
        request_serializer=map__pb2.Message.SerializeToString,
        response_deserializer=map__pb2.Response.FromString,
        )
    self.Exit = channel.unary_unary(
        '/Map/Exit',
        request_serializer=map__pb2.Message.SerializeToString,
        response_deserializer=map__pb2.Response.FromString,
        )


class MapServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendGrpc(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LogTest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Retrieve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Exit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MapServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendGrpc': grpc.unary_unary_rpc_method_handler(
          servicer.SendGrpc,
          request_deserializer=map__pb2.Message.FromString,
          response_serializer=map__pb2.Response.SerializeToString,
      ),
      'LogTest': grpc.unary_unary_rpc_method_handler(
          servicer.LogTest,
          request_deserializer=map__pb2.Message.FromString,
          response_serializer=map__pb2.Data.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=map__pb2.Message.FromString,
          response_serializer=map__pb2.Response.SerializeToString,
      ),
      'Retrieve': grpc.unary_unary_rpc_method_handler(
          servicer.Retrieve,
          request_deserializer=map__pb2.Message.FromString,
          response_serializer=map__pb2.Response.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=map__pb2.Message.FromString,
          response_serializer=map__pb2.Response.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=map__pb2.Message.FromString,
          response_serializer=map__pb2.Response.SerializeToString,
      ),
      'Exit': grpc.unary_unary_rpc_method_handler(
          servicer.Exit,
          request_deserializer=map__pb2.Message.FromString,
          response_serializer=map__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Map', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
