# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sd_work.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sd_work.proto',
  package='sd_work',
  syntax='proto3',
  serialized_pb=_b('\n\rsd_work.proto\x12\x07sd_work\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\x0c\" \n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\">\n\x0eServerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1b\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\r.sd_work.Data2\xd2\x01\n\x06Server\x12\x32\n\x06\x63reate\x12\r.sd_work.Data\x1a\x17.sd_work.ServerResponse\"\x00\x12.\n\x04read\x12\x0b.sd_work.Id\x1a\x17.sd_work.ServerResponse\"\x00\x12\x32\n\x06update\x12\r.sd_work.Data\x1a\x17.sd_work.ServerResponse\"\x00\x12\x30\n\x06\x64\x65lete\x12\x0b.sd_work.Id\x1a\x17.sd_work.ServerResponse\"\x00\x62\x06proto3')
)




_ID = _descriptor.Descriptor(
  name='Id',
  full_name='sd_work.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sd_work.Id.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=42,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='sd_work.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sd_work.Data.id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='sd_work.Data.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=76,
)


_SERVERRESPONSE = _descriptor.Descriptor(
  name='ServerResponse',
  full_name='sd_work.ServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='sd_work.ServerResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='sd_work.ServerResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=140,
)

_SERVERRESPONSE.fields_by_name['data'].message_type = _DATA
DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['ServerResponse'] = _SERVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), dict(
  DESCRIPTOR = _ID,
  __module__ = 'sd_work_pb2'
  # @@protoc_insertion_point(class_scope:sd_work.Id)
  ))
_sym_db.RegisterMessage(Id)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'sd_work_pb2'
  # @@protoc_insertion_point(class_scope:sd_work.Data)
  ))
_sym_db.RegisterMessage(Data)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVERRESPONSE,
  __module__ = 'sd_work_pb2'
  # @@protoc_insertion_point(class_scope:sd_work.ServerResponse)
  ))
_sym_db.RegisterMessage(ServerResponse)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='sd_work.Server',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=143,
  serialized_end=353,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='sd_work.Server.create',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_SERVERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='sd_work.Server.read',
    index=1,
    containing_service=None,
    input_type=_ID,
    output_type=_SERVERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='sd_work.Server.update',
    index=2,
    containing_service=None,
    input_type=_DATA,
    output_type=_SERVERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='sd_work.Server.delete',
    index=3,
    containing_service=None,
    input_type=_ID,
    output_type=_SERVERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
