# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_side.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_side.proto',
  package='server_side',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11server_side.proto\x12\x0bserver_side\"J\n\nServerInfo\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0c\n\x04next\x18\x02 \x01(\t\x12\x0c\n\x04\x62\x61\x63k\x18\x03 \x01(\t\x12\x10\n\x08serverID\x18\x04 \x01(\x03\x32}\n\x03P2P\x12:\n\x04join\x12\x17.server_side.ServerInfo\x1a\x17.server_side.ServerInfo\"\x00\x12:\n\x04\x65xit\x12\x17.server_side.ServerInfo\x1a\x17.server_side.ServerInfo\"\x00\x62\x06proto3')
)




_SERVERINFO = _descriptor.Descriptor(
  name='ServerInfo',
  full_name='server_side.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='server_side.ServerInfo.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next', full_name='server_side.ServerInfo.next', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='back', full_name='server_side.ServerInfo.back', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverID', full_name='server_side.ServerInfo.serverID', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), dict(
  DESCRIPTOR = _SERVERINFO,
  __module__ = 'server_side_pb2'
  # @@protoc_insertion_point(class_scope:server_side.ServerInfo)
  ))
_sym_db.RegisterMessage(ServerInfo)



_P2P = _descriptor.ServiceDescriptor(
  name='P2P',
  full_name='server_side.P2P',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=110,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='join',
    full_name='server_side.P2P.join',
    index=0,
    containing_service=None,
    input_type=_SERVERINFO,
    output_type=_SERVERINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='exit',
    full_name='server_side.P2P.exit',
    index=1,
    containing_service=None,
    input_type=_SERVERINFO,
    output_type=_SERVERINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_P2P)

DESCRIPTOR.services_by_name['P2P'] = _P2P

# @@protoc_insertion_point(module_scope)
