// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcClient.proto

package io.grpc;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_grpc_GenericRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_grpc_GenericRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_grpc_GenericResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_grpc_GenericResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020GrpcClient.proto\022\007io.grpc\",\n\016GenericRe" +
      "quest\022\014\n\004code\030\001 \001(\005\022\014\n\004data\030\002 \001(\t\"@\n\017Gen" +
      "ericResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030" +
      "\002 \001(\t\022\014\n\004data\030\003 \001(\t2\202\002\n\007Greeter\022=\n\006Creat" +
      "e\022\027.io.grpc.GenericRequest\032\030.io.grpc.Gen" +
      "ericResponse\"\000\022:\n\003Get\022\027.io.grpc.GenericR" +
      "equest\032\030.io.grpc.GenericResponse\"\000\022=\n\006Up" +
      "date\022\027.io.grpc.GenericRequest\032\030.io.grpc." +
      "GenericResponse\"\000\022=\n\006Delete\022\027.io.grpc.Ge" +
      "nericRequest\032\030.io.grpc.GenericResponse\"\000" +
      "B\036\n\007io.grpcB\013ClientProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_grpc_GenericRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_grpc_GenericRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_grpc_GenericRequest_descriptor,
        new String[] { "Code", "Data", });
    internal_static_io_grpc_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_grpc_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_grpc_GenericResponse_descriptor,
        new String[] { "Status", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
